[package]
name = "muse"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.17.3"
toml = "0.8.8"
colored = "2.1.0"
serde_json = "1.0.111"
serde = { version = "1.0.195", features = ["derive"] }
lofty = "0.18.0"
home = "0.5.9"
clap = "4.4.18"
